apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KubernikusControlPlane
metadata:
  labels:
    app.kubernetes.io/name: kubernikuscontrolplane
    app.kubernetes.io/instance: kubernikuscontrolplane-sample
    app.kubernetes.io/part-of: cluster-api-control-plane-provider-kubernikus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-control-plane-provider-kubernikus
  name: kubernikuscontrolplane-sample
spec:
  # TODO(user): Add fields here
